"""
Django settings for gestao_clientes project.

Generated by 'django-admin startproject' using Django 2.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Secao 5. Aula 29, os 2 imports
from decouple import config
from dj_database_url import parse as dburl

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# Secao 5, aula 29. Caso nao consiga achar o arquivo, entao Padrao = False e fas um CAST para BOOL 08:30
DEBUG = config('DEBUG', default=False, cast=bool)

# Secao 5, aula 31 01:00
ALLOWED_HOSTS = ['gescli.herokuapp.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'clientes',
    'home',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gestao_clientes.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gestao_clientes.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases
# Usou o link acima em Secao 4, video 25

# 09:40
# Secao 5. Aula 29 removendo as configs do banco de dados e adicionando o conteudo abaixo
# Vai montar a URL de Banco de Dados, considerando o Banco de Dados Sqlite3 para o seu banco local
# Mas, se encontrar uma configuracao de banco de dados, ele vai usar essa configuracao
default_dburl = 'sqlite:///' + os.path.join(BASE_DIR, 'db.sqlite3')

DATABASES = { 
    'default': config('DATABASE_URL', default=default_dburl, cast=dburl), 
}



# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'


MEDIA_URL = '/media/'

# eh a PASTA REAL, com a SUBPASTA clients_photos que esta localizano no MODEL de clientes no atributo PHOTO em upload_to
MEDIA_ROOT = 'medias'


# Secao 4, video 23
# Definir a URL de login
LOGIN_URL = 'login'

# Para onde vai mandar quando o usuario fizer login. Secao 4, Video 23 ou 24. Acredito que eh o 23
LOGIN_REDIRECT_URL = 'persons_list'


# Commit da Secao 4 inteira 26-04-2018 - 14:00

# Secao 5, video 29
# Inicio de deploy no heroku
# https://github.com/Gpzim98/django-heroku

# Secao 5, aula 29
# Vai alimentar a variavel STATIC_ROOT, com o nome da pasta que a gente quer, no caso staticfiles
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')